appId: com.livelatex.app
productName: LiveLaTeX
copyright: Copyright © 2025

directories:
  output: release
  buildResources: assets

files:
  - dist/**/*
  - node_modules/**/*.js
  - node_modules/**/*.mjs
  - node_modules/**/*.json
  - "!node_modules/**/test"
  - "!node_modules/**/docs"
  - "!node_modules/**/demo"
  - "!node_modules/**/example"
  - "!node_modules/**/*.map"

extraResources:
  - from: texlive/TinyTeX
    to: texlive/TinyTeX
    filter:
      - "**/*"

asar: true
asarUnpack:
  - node_modules/chokidar/**
  - node_modules/electron-store/**
  - "**/*.node"

win:
  target:
    - target: portable
      arch:
        - x64
    - target: nsis
      arch:
        - x64

nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: LiveLaTeX
  artifactName: LiveLaTeX-Setup-${version}.${ext}

portable:
  artifactName: LiveLaTeX-Portable-${version}.${ext}
  requestExecutionLevel: user

extraMetadata:
  main: dist/main/index.js
