// ─── Incremental self-update ─────────────────────────────────────
//
// The distributable zip carries ~600MB of TinyTeX nobody wants to re-download
// for an app fix. So updates ship as a small app-only bundle: the release
// asset `LiveLaTeX-app-<version>.zip` containing resources/app.asar and
// resources/app.asar.unpacked (the TeX tree stays untouched on disk).
//
// Flow: check GitHub latest release → download asset → extract into
// resources/update-pending/ → relaunch → on next boot applyPendingUpdate()
// swaps the files in (they are locked while the app runs, hence the reboot).

const { app, ipcMain } = require('electron');
const { spawn } = require('child_process');
const fs = require('fs');
const path = require('path');
const https = require('https');
const { log } = require('./logger');

const REPO_API = 'https://api.github.com/repos/foxhank/LatexLive/releases/latest';
const RESOURCES = () => process.resourcesPath;
const pendingDir = () => path.join(RESOURCES(), 'update-pending');

let status = { phase: 'idle', detail: '', progress: 0, version: '', releaseUrl: '', currentVersion: '' };
let getWin = () => null;

function setStatus(phase, detail = '', progress = 0, version = '') {
  status = {
    ...status, phase, detail, progress,
    version: version || status.version,
    releaseUrl: phase === 'available-manual' ? 'https://github.com/foxhank/LatexLive/releases/latest' : status.releaseUrl,
  };
  const win = getWin();
  if (win && !win.isDestroyed()) win.webContents.send('update:status', status);
  log('INFO', `[update] ${phase} ${detail} ${(progress * 100).toFixed(0)}%`);
}

// ─── Swap-in at install time ─────────────────────────────────────

// app.asar is held open by the running process, so it can't be replaced from
// inside. Spawn a detached batch file that waits for this process to exit,
// swaps the files (with retries), then relaunches the app.
function launchSwapScript() {
  const pend = pendingDir();
  const res = RESOURCES();
  const appExe = app.getPath('exe');
  const bat = path.join(pend, 'apply-update.bat');
  const script = [
    '@echo off',
    'rem Generated by LiveLaTeX updater — waits for app exit, swaps app.asar, relaunches',
    'ping -n 4 127.0.0.1 >nul',
    `set /a tries=0`,
    ':retryasar',
    `move /y "${path.join(pend, 'app.asar')}" "${path.join(res, 'app.asar')}" >nul 2>&1`,
    'if %errorlevel% neq 0 (',
    '  set /a tries+=1',
    '  if %tries% lss 15 (ping -n 2 127.0.0.1 >nul & goto retryasar)',
    '  echo swap failed, aborting & exit /b 1',
    ')',
    `if exist "${path.join(pend, 'app.asar.unpacked')}" (`,
    `  rmdir /s /q "${path.join(res, 'app.asar.unpacked')}"`,
    `  move "${path.join(pend, 'app.asar.unpacked')}" "${path.join(res, 'app.asar.unpacked')}" >nul 2>&1`,
    ')',
    'rmdir /s /q "' + pend + '"',
    `start "" "${appExe}"`,
    'del "%~f0"',
  ].join('\r\n');
  fs.writeFileSync(bat, script, 'utf-8');
  const child = spawn('cmd.exe', ['/d', '/c', bat], { detached: true, stdio: 'ignore', windowsHide: true });
  child.unref();
  log('INFO', `[update] swap script launched (${bat})`);
}

// ─── GitHub release check + download ─────────────────────────────

function httpsGetJson(url) {
  return new Promise((resolve, reject) => {
    https.get(url, { headers: { 'User-Agent': 'livelatex-updater', 'Accept': 'application/vnd.github+json' } }, (res) => {
      if (res.statusCode !== 200) { res.resume(); return reject(new Error(`HTTP ${res.statusCode}`)); }
      let d = '';
      res.on('data', (c) => (d += c));
      res.on('end', () => { try { resolve(JSON.parse(d)); } catch (e) { reject(e); } });
    }).on('error', reject);
  });
}

function httpsDownload(url, dest, onProgress) {
  return new Promise((resolve, reject) => {
    const get = (u) => {
      https.get(u, { headers: { 'User-Agent': 'livelatex-updater' } }, (res) => {
        if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
          res.resume();
          return get(res.headers.location);
        }
        if (res.statusCode !== 200) { res.resume(); return reject(new Error(`HTTP ${res.statusCode}`)); }
        const total = Number(res.headers['content-length'] || 0);
        let done = 0;
        const file = fs.createWriteStream(dest);
        res.on('data', (c) => {
          done += c.length;
          if (total) onProgress(done / total);
        });
        res.pipe(file);
        file.on('finish', () => file.close(() => resolve(dest)));
        file.on('error', reject);
      }).on('error', reject);
    };
    get(url);
  });
}

function parseVersion(tag) {
  const m = String(tag || '').match(/(\d+)\.(\d+)\.(\d+)/);
  return m ? [Number(m[1]), Number(m[2]), Number(m[3])] : null;
}

function isNewer(remote, local) {
  const r = parseVersion(remote);
  const l = parseVersion('v' + app.getVersion());
  if (!r || !l) return false;
  for (let i = 0; i < 3; i++) {
    if (r[i] !== l[i]) return r[i] > l[i];
  }
  return false;
}

async function checkAndDownload() {
  if (!app.isPackaged) {
    setStatus('idle', '开发模式不检查更新');
    return status;
  }
  try {
    setStatus('checking', '正在检查更新…');
    const rel = await httpsGetJson(REPO_API);
    const remoteVer = String(rel.tag_name || '').replace(/^v/, '');
    if (!isNewer(rel.tag_name, app.getVersion())) {
      setStatus('up-to-date', `已是最新版本 v${app.getVersion()}`);
      return status;
    }
    const asset = (rel.assets || []).find((a) => a.name === `LiveLaTeX-app-${remoteVer}.zip`);
    if (!asset) {
      // App-only bundle missing (older release layout) — point at the full zip
      setStatus('available-manual', `发现新版本 v${remoteVer}，请在发布页下载完整包`);
      return status;
    }
    setStatus('available', `发现新版本 v${remoteVer}`, 0, remoteVer);

    const tmpZip = path.join(app.getPath('temp'), `livelatex-update-${remoteVer}.zip`);
    await httpsDownload(asset.browser_download_url, tmpZip, (p) => setStatus('downloading', `下载中 ${(p * 100).toFixed(0)}%`, p, remoteVer));

    setStatus('extracting', '正在解压更新包…', 1, remoteVer);
    const pend = pendingDir();
    fs.rmSync(pend, { recursive: true, force: true });
    fs.mkdirSync(pend, { recursive: true });
    await new Promise((resolve, reject) => {
      // Expand-Archive ships with Windows 10+; no unzip dependency needed
      spawn('powershell.exe', [
        '-NoProfile', '-NonInteractive', '-WindowStyle', 'Hidden', '-Command',
        `Expand-Archive -LiteralPath "${tmpZip}" -DestinationPath "${pend}" -Force`,
      ], { windowsHide: true }).on('exit', (code) => (code === 0 ? resolve() : reject(new Error(`解压失败 (exit ${code})`))));
    });
    if (!fs.existsSync(path.join(pend, 'app.asar'))) throw new Error('更新包内容不完整');
    try { fs.rmSync(tmpZip, { force: true }); } catch {}
    setStatus('ready', `v${remoteVer} 已就绪，重启后生效`, 1, remoteVer);
    return status;
  } catch (e) {
    log('ERROR', `[update] failed: ${e.message}`);
    setStatus('error', `更新失败：${e.message}`);
    return status;
  }
}

function initUpdate(opts_) {
  getWin = opts_.getWin || getWin;
  status.currentVersion = 'v' + app.getVersion();

  ipcMain.handle('update:check', () => checkAndDownload());
  ipcMain.handle('update:state', () => status);
  ipcMain.handle('update:install', () => {
    if (status.phase !== 'ready') return { ok: false, error: '没有待安装的更新' };
    try {
      launchSwapScript();
      app.exit(0);
      return { ok: true };
    } catch (e) {
      log('ERROR', `[update] install failed: ${e.message}`);
      return { ok: false, error: e.message };
    }
  });
}

// Silent check shortly after startup; progress surfaces via 'update:status'
function startupCheck() {
  setTimeout(() => {
    checkAndDownload().catch(() => {});
  }, 4000);
}

module.exports = { initUpdate, startupCheck };
